Homework №1

In [10]:
import numpy as np

In [11]:
vector1 = np.arange(1, 6) ** 2
print(vector1)

[ 1  4  9 16 25]


In [12]:
matrix = np.zeros((3, 3), dtype = int)

nums = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]

current_number = 1
counter = 0

small1 = 0
small2 = 0
for i in range(3):
    for j in range(3):
        
        if nums[counter] < current_number:
            small1 = small2
            small2 = nums[counter]
            counter += 1
        
        matrix[i, j] = small2 * small1
        current_number += 1
        
print("Матриця:")
print(matrix)

Матриця:
[[ 0  0  0]
 [ 6  6 15]
 [15 35 35]]


In [13]:
n = 8
m = 8

matrix = np.random.randint(1, 11, (n, m))

harmonic = n * m / np.sum(1 / matrix)

print("Matrix:\n", matrix)
print("\nHarmonic:", harmonic)

Matrix:
 [[ 3  1  4  2  8  4  2  8]
 [ 6 10  3  2  5 10  2  2]
 [ 8  1  4  1  6  4 10  7]
 [ 7  8  4  7  8  7 10  4]
 [ 8  9  3  7  9  2  2  6]
 [ 1 10  2  3  8  7  8  2]
 [ 9  5  8  5  9  2  1  4]
 [ 3  3  9  1  7  1  9  9]]

Harmonic: 3.1600603483747083


In [14]:
matrix = np.random.uniform(0, 10, (3, 3))

min_column_elems = np.min(matrix, axis = 1)

print("Matrix:", matrix)
print("\nColumn with minimum elements:", min_column_elems)

Matrix: [[5.49878279 8.7974876  9.29692159]
 [8.92220681 1.15223899 7.72676555]
 [4.87719375 4.1188166  5.39188971]]

Column with minimum elements: [5.49878279 1.15223899 4.1188166 ]


In [15]:
array1 = np.random.rand(6)
array2 = np.random.rand(6)

print("First array", array1) 
print("Second array", array2)

adding_arrays = array1 + array2
subtraction_arrays = array1 - array2
multiplication_arrays = array1 * array2

print("\nAdding:", adding_arrays)
print("\nSubtraction:", subtraction_arrays)
print("\nMultiplication:", multiplication_arrays)

First array [0.83676369 0.16751767 0.84089825 0.03912263 0.28477333 0.86554752]
Second array [0.79955081 0.95793798 0.57620062 0.0940046  0.46784605 0.95407852]

Adding: [1.6363145  1.12545565 1.41709887 0.13312723 0.75261938 1.81962603]

Subtraction: [ 0.03721287 -0.79042031  0.26469763 -0.05488197 -0.18307272 -0.088531  ]

Multiplication: [0.66903509 0.16047154 0.48452609 0.00367771 0.13323008 0.82580029]


In [16]:
vector1 = np.array([1, 3, 5, 7, 9, 11, 13, 15])
vector2 = np.array([2, 4, 6, 8, 10, 12, 14, 16])

scalar_product = np.dot(vector1, vector2)

print(scalar_product)

744


In [17]:
matrix1 = np.random.randint(1, 21, (3, 2))
matrix2 = np.random.randint(1, 21, (2, 4))

multiplication_matrix = np.dot(matrix1, matrix2)

print("Matrix1:\n", matrix1)
print("\nMatrix2: \n", matrix2)
print("\nMultiplication: \n", multiplication_matrix)

Matrix1:
 [[17  8]
 [ 3  6]
 [ 5 15]]

Matrix2: 
 [[10  2 10 17]
 [18  7  9 13]]

Multiplication: 
 [[314  90 242 393]
 [138  48  84 129]
 [320 115 185 280]]


In [18]:
matrix = np.random.randint(1, 9, (2, 2))
print("Matrix: \n", matrix)

inverse_matrix = np.linalg.inv(matrix)
print("\nInverse matrix: \n", inverse_matrix)

Matrix: 
 [[7 7]
 [7 2]]

Inverse matrix: 
 [[-0.05714286  0.2       ]
 [ 0.2        -0.2       ]]


In [19]:
matrix = np.random.randint(0, 2, (3, 3))
print("Matrix: \n", matrix)

transp_matrix = np.transpose(matrix)
print("\nTransparent matrix: \n", transp_matrix)


Matrix: 
 [[1 0 1]
 [0 0 0]
 [1 1 1]]

Transparent matrix: 
 [[1 0 1]
 [0 0 1]
 [1 0 1]]


In [20]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size = 4)
print("Matrix:\n", matrix)
print("\nVector:\n", vector)

result = np.dot(matrix, vector)
print("\nResult of multiplication:\n", result)

Matrix:
 [[0.46198561 0.78065547 0.4884487  0.63923616]
 [0.33089017 0.62338013 0.91670829 0.42902268]
 [0.94629084 0.68688727 0.96494219 0.64787708]]

Vector:
 [6 5 4 4]

Result of multiplication:
 [11.18593046 10.48516553 15.56345845]


In [21]:
matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.randint(1, 11, size = 3)
print("Matrix:\n", matrix)
print("\nVector:\n", vector)

mean_vector = np.mean(vector)
print("\nMean value of the vector:\n", mean_vector)

elems = matrix[matrix > mean_vector]
print("\nElements bigger than mean of vector:\n", elems)

sum_of_elems = np.sum(elems)
print("\nSum of elements bigger than mean of vector:\n", sum_of_elems)

Matrix:
 [[9 5 3]
 [6 3 2]]

Vector:
 [5 8 3]

Mean value of the vector:
 5.333333333333333

Elements bigger than mean of vector:
 [9 6]

Sum of elements bigger than mean of vector:
 15


In [22]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Matrix 1:\n", matrix1)

sum_of_diagonal = np.trace(matrix1)

print("\nThe sum of the elements of the diagonal of the first matrix:", sum_of_diagonal)

Matrix 1:
 [[ 9  7]
 [10  8]]

The sum of the elements of the diagonal of the first matrix: 17


In [26]:
matrix1 = np.random.rand(9, 9)
matrix2 = np.random.rand(9, 9)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

sum_of_elems = matrix1 + matrix2
print("\nSum of the elements:\n", sum_of_elems)

Matrix 1:
 [[0.57321278 0.68668209 0.73859077 0.13857288 0.83508415 0.21104885
  0.67279995 0.10645234 0.88058433]
 [0.46210814 0.75168775 0.14330675 0.71083471 0.13677054 0.9639331
  0.96607196 0.17226537 0.90655043]
 [0.99116761 0.12188785 0.68834575 0.86224114 0.65518422 0.71549283
  0.90790339 0.45983681 0.68405066]
 [0.2926716  0.67812853 0.83448158 0.68811034 0.32971491 0.45131643
  0.87350562 0.33942418 0.94397047]
 [0.64691789 0.79068225 0.58346601 0.20233372 0.6284452  0.90138853
  0.02967527 0.04023748 0.87371981]
 [0.72792672 0.95605193 0.34706829 0.85879862 0.78434623 0.01054808
  0.59835269 0.65748307 0.46034196]
 [0.92765845 0.59008868 0.27178275 0.66811116 0.43106904 0.67028747
  0.03276367 0.96307958 0.94731691]
 [0.61930458 0.88826026 0.01115495 0.7724906  0.83532103 0.24438377
  0.72602791 0.09216999 0.91275933]
 [0.72671934 0.96907733 0.04324233 0.26180104 0.63718158 0.2492675
  0.26146856 0.19087923 0.94092171]]

Matrix 2:
 [[3.84878779e-01 6.46766208e-01 3.31706364

In [27]:
matrix = np.random.uniform(-10, 10, (9, 9))
print("Matrix:\n", matrix)

geometric_mean = np.prod(matrix) ** (1 / np.size(matrix))
print("\nGeometric mean of all elements of matrix:\n", geometric_mean)

Matrix:
 [[ 0.72305574  2.38152415 -9.70163324 -4.52486974 -7.46055726 -3.41605179
  -7.84551645 -8.45724841 -7.98937532]
 [ 4.46455508  9.32622658 -1.95124403 -3.18717141 -4.1600607   9.53492317
   2.99670041 -6.94777355  2.03549196]
 [ 6.82774425  7.95652378  5.21748282 -4.7177697  -1.20319866 -5.74289152
   6.27215532 -5.10942122  9.94101715]
 [ 1.49297619  9.97272656  3.49124625 -8.59212629 -5.07166313 -0.81491809
  -5.8889984  -8.59966159  6.54968531]
 [ 3.87027445  2.46447877 -8.6497328   1.01196606 -0.65476394  9.93912469
   7.80565906 -3.85221472 -3.96378006]
 [-3.90451377 -0.44476676  7.31337097  7.56071095 -6.55073632 -4.74443246
  -8.19957555  6.71113841  8.53488005]
 [-6.60579962 -5.21653074 -2.2259888   1.64796744  6.78909505 -3.36386864
   1.6137316  -2.14278487 -8.18976598]
 [ 4.53631917 -5.51031289  5.81257599 -5.79719553 -8.38553404 -9.48324748
  -9.8694855   6.65002295 -8.42719247]
 [-8.71434538  1.05857993 -5.3760313   4.95325245 -0.3333744   5.86046221
   0.41258802

In [25]:
matrix = np.random.rand(3, 3)
print("Matrix:\n", matrix)

positive_elems = np.sum(matrix > 0, axis = 1)
print("\nVector of positive elements of each row in matrix:\n", positive_elems)

Matrix:
 [[0.64495988 0.70486046 0.17105582]
 [0.48876335 0.18432745 0.30141565]
 [0.75410432 0.86346428 0.64428804]]

Vector of positive elements of each row in matrix:
 [3 3 3]
